release/v0.6.0
rafia37/Evolution-of-Galaxies pull request #28
Opened 2020-05-05 00:55 UTC by cmccormick1

Includes implementing MSC's error_prop functions and plotting temperature and metallicity error bars for composite measurements.

2020-05-16 22:05 UTC, astrochun requested changes
See comments for suggestions and possible typo

2020-05-16 22:05 UTC, astrochun commented on general.py
> +    valid_file = fitspath + filename_dict['bin_valid']
You might consider using `os.path.join` to define paths.  This handles the extraneous `/` in path.
`from os.path import join`
`valid_file = join(fitspath, filename_dict['bin_valid'])`

2020-05-16 22:05 UTC, astrochun commented on plots.py
> +        metal_low_err = [metal_err[ii][0] for ii in range(len(metal_err))]
I think you can do: `metal_low_err = metal_err[:,0]` and similarly for `metal_high_err`

2020-05-16 22:05 UTC, astrochun commented on plots.py
> +        metal_low_err_M = [metal_err_M[ii][0] for ii in range(len(metal_err_M))]
It seems that you do this often, extract one of the errorbars.  You might consider creating a function that provides both lower and upper errors.

2020-05-16 22:05 UTC, astrochun commented on plots.py
> +        ax11[0].errorbar(LHb_avg_mass[LHb_detect], LHb_metal[LHb_detect], yerr = metal_lowhigh_err_LHb, fmt = '.')
I think there's a mistake in line 582 as it should be `ax11[1]`

2020-05-16 22:05 UTC, astrochun commented on general.py
> +        plots.bin_derived_props_plots(fitspath, metal_file, em_file, bin_file, valid_file, out_fname, hbeta_bin = bool_hbeta_bin, err_bars = True)
Should there handling for `error_prop == False`?

2020-05-16 22:05 UTC, astrochun commented on plots.py
> +        Te_low_err = np.log10(1 + (Te_low_err)/T_e[detect])
I believe for low error this should be
`Te_low_err = -1*np.log10(1 - Te_low_err/T_e[detect])`

2020-05-16 22:05 UTC, astrochun commented on general.py
>      if err_prop == True:
Note that you can simplify to: `if err_prop:` (this handles boolean true/false or binary 1/0)

2020-05-16 22:05 UTC, astrochun commented on plots.py
> +        der_prop_err_LHb = np.load(fitspath + 'massbin/' + dataset + npz_filename_dict['der_prop_errors'])
`os.path.join` would make this easier as it accepts multiple folders as separate inputs:
`join(fitspath, 'massbin', dataset, npz_filename_dict['der_prop_errors'])`

2020-05-16 22:05 UTC, astrochun commented on plots.py
> +        metal_low_err_M = [metal_err_M[ii][0] for ii in range(len(metal_err_M))]
There might also be a way of using `numpy.transpose` to flip the error arrays for `matplotlib`

2020-05-18 17:21 UTC, cmccormick1 commented on plots.py
> +        metal_low_err_M = [metal_err_M[ii][0] for ii in range(len(metal_err_M))]
Yes, I was considering making a separate function for extracting error bars, but I was going to change it on my feature/plots_reorganize branch.

2020-05-18 17:33 UTC, merged