release/v0.8.0
rafia37/Evolution-of-Galaxies pull request #41
Opened 2020-07-10 16:02 UTC by cmccormick1

This PR supersedes PR #40 

Includes:
   1. The reorganization of analysis codes into an Analysis sub-folder (see issue #31 and PR #33): feature/reorganize
   2. The updating of R_temp_calcul.py to include most recent changes in MSC (see issue #34 and PR #35): feature/R_temp_calcul
   3. The updating of indiv_gals.py to include most recent changes in MSC (see issue #38 and PR #39): feature/indiv_gals

2020-07-17 16:06 UTC, astrochun requested changes
Most minor suggestions and ways to improve.

2020-07-17 16:06 UTC, astrochun commented on Analysis/indiv_gals.py
> +
```suggestion
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/R_temp_calcul.py
> +from Metallicity_Stack_Commons.analysis.temp_metallicity_calc import temp_calculation, metallicity_calculation
```suggestion

from Metallicity_Stack_Commons.analysis.temp_metallicity_calc import temp_calculation, metallicity_calculation 
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/R_temp_calcul.py
> +    bin_table = asc.read(bin_file, format = 'fixed_width_two_line')
```suggestion
    # Case for stacked spectra
    print("Reading : ", bin_file)
    bin_table = asc.read(bin_file, format='fixed_width_two_line')
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/R_temp_calcul.py
> +    line_table = asc.read(line_file)
```suggestion
    print("Reading : ", line_file)
    line_table = asc.read(line_file)
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/R_temp_calcul.py
> +    three_beta = flux_ratios_dict['three_beta']
You actually don't need to define this.  Instead, you can pass in `flux_ratios_dict[]` in lines 52 and 54-57

2020-07-17 16:06 UTC, astrochun commented on Analysis/R_temp_calcul.py
> +    tab0.write(outfile.replace('.tbl', '.fits'), format = 'fits', overwrite = True)
```suggestion
    print("Writing : ", outfile)
    asc.write(tab0, outfile, format='fixed_width_two_line', overwrite=True)
    tab0.write(outfile.replace('.tbl', '.fits'), format='fits', overwrite=True) 
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/R_temp_calcul.py
> +                  metal_dict['O++/H']], names = n)
You might consider separating the table content as a separate `list` and then it would look like:
`tab0 = Table(table_list, names=n)`

2020-07-17 16:06 UTC, astrochun commented on Analysis/indiv_gals.py
> +
```suggestion
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/indiv_gals.py
> +from Metallicity_Stack_Commons.column_names import filename_dict, bin_names0, bin_mzevolve_names0, indv_names0, line_fit_suffix_add
```suggestion

from Metallicity_Stack_Commons.column_names import filename_dict, bin_names0, bin_mzevolve_names0, indv_names0, line_fit_suffix_add
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/indiv_gals.py
> +from Metallicity_Stack_Commons.column_names import filename_dict, bin_names0, bin_mzevolve_names0, indv_names0, line_fit_suffix_add
Also, try to keep lines of codes < 80 characters for readability.

2020-07-17 16:06 UTC, astrochun commented on Analysis/indiv_gals.py
> +    #Convert bin info table into a dictionary
```suggestion
    # Convert bin info table into a dictionary
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/indiv_gals.py
> +    bin_idx = bin_npz['bin_ind']     #valid mass bin indices relative to unsorted data table
```suggestion
    bin_idx = bin_npz['bin_ind']  # valid mass bin indices relative to unsorted data table 
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/indiv_gals.py
> +    #Get all bin valid values in dictionary
```suggestion
    # Get all bin valid values in dictionary
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/indiv_gals.py
> +    indiv_dict[indv_names0[0]] = objno[idx_array]      #ID
Consider initializing with `np.zeros()` and then using the `bin_idx[ii]` to populate so that there's a row-by-row match.

2020-07-17 16:06 UTC, astrochun commented on Analysis/indiv_gals.py
> +    asc.write(indiv_dict, names = tuple(bin_cols), output = out_ascii, format = 'fixed_width_two_line', overwrite = True)
```suggestion
    out_ascii = fitspath + filename_dict['indv_bin_info']
    asc.write(indiv_dict, names=tuple(bin_cols), output=out_ascii, format='fixed_width_two_line', overwrite=True)
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/indiv_gals.py
> +
```suggestion
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/indiv_gals.py
> +    asc.write(data, names = tuple([indv_names0[0]] + indv_names0[3:5] + cols), output = out_ascii, format = 'fixed_width_two_line', overwrite = True)
```suggestion
    asc.write(data, names=tuple([indv_names0[0]] + indv_names0[3:5] + cols), output=out_ascii, format='fixed_width_two_line', overwrite = True)

```

2020-07-17 16:06 UTC, astrochun commented on Plotting/individual_plots.py
>      if revised == True:
```suggestion
    if revised:
```

2020-07-17 16:06 UTC, astrochun commented on Plotting/composite_plots.py
>  from Metallicity_Stack_Commons.column_names import temp_metal_names0, bin_ratios0, bin_mzevolve_names0
```suggestion

from Metallicity_Stack_Commons.column_names import temp_metal_names0, bin_ratios0, bin_mzevolve_names0
```

2020-07-17 16:06 UTC, astrochun commented on Plotting/composite_plots.py
>      #Define detection and non-detection (with reliable 5007) arrays
```suggestion
    # Define detection and non-detection (with reliable 5007) arrays
```

2020-07-17 16:06 UTC, astrochun commented on Plotting/individual_plots.py
>      #Read in individual data
```suggestion
    # Read in individual data
```

2020-07-17 16:06 UTC, astrochun commented on Plotting/composite_plots.py
>      logLHb_avg = bin_table[bin_mzevolve_names0[6]].data
Are these definitions being used? I didn't easily see where.

2020-07-17 16:06 UTC, astrochun commented on general.py
> +from Evolution_of_Galaxies.Analysis import library, emission_line_fit, indiv_gals, R_temp_calcul
```suggestion

from Evolution_of_Galaxies.Analysis import library, emission_line_fit, indiv_gals, R_temp_calcul
```

2020-07-17 16:06 UTC, astrochun commented on general.py
>  from Evolution_of_Galaxies.Plotting.relation_fitting import extract_error_bars
You might consider doing relative imports here.

2020-07-17 16:06 UTC, astrochun commented on general.py
> +
```suggestion
```

2020-07-17 16:06 UTC, astrochun commented on general.py
> +    return {cols[ii]:tbl[cols[ii]].data for ii in range(len(cols))}
There might be an easier way with an astropy built-in feature

2020-07-17 16:06 UTC, astrochun commented on general.py
>  from Metallicity_Stack_Commons import get_user, dir_date, fitting_lines_dict
```suggestion

from Metallicity_Stack_Commons import get_user, dir_date, fitting_lines_dict
```

2020-07-17 16:06 UTC, astrochun commented on general.py
>      if bool_hbeta_bin == True:
```suggestion
    if bool_hbeta_bin:
```

2020-07-17 16:06 UTC, astrochun commented on general.py
>          detect[11] = 0.5
This looks like a manual fix

2020-07-17 16:06 UTC, astrochun commented on general.py
> +    valid_file = fitspath + filename_dict['bin_valid_rev']
There's a lot of use of this file throughout this section of coding.  Defining it earlier might help and simplify readability.

2020-07-17 16:06 UTC, astrochun commented on general.py
>      #Run plots
```suggestion
    # Run plots
```

2020-07-17 16:06 UTC, astrochun commented on general.py
>          #Create individual_bin_info table
```suggestion
    if indiv:
        # Create individual_bin_info table
```

2020-07-17 16:06 UTC, astrochun commented on general.py
> +        indiv_gals.indiv_bin_info_table(fitspath, line_file, use_revised = True)
```suggestion
        indiv_gals.indiv_bin_info_table(fitspath, line_file, use_revised=True)
```

2020-07-17 16:06 UTC, astrochun commented on general.py
>          main(fitspath, '', revised = False, det3 = True)
```suggestion
        main(fitspath, '', revised=False, det3=True)
```

2020-07-17 16:06 UTC, astrochun commented on Analysis/R_temp_calcul.py
> +    tab0 = Table([bin_IDs, logR23, logO32, two_beta, three_beta, R, T_e, metal_dict['12+log(O/H)'],
It might be easier since most of the content is in two dictionaries to create a new dictionary and append using the `dict.update()` option

2020-07-17 16:06 UTC, astrochun commented on Plotting/individual_plots.py
>      #Read in composite data tables
```suggestion
    # Read in composite data tables
```

2020-07-23 22:05 UTC, cmccormick1 commented on Plotting/composite_plots.py
>      logLHb_avg = bin_table[bin_mzevolve_names0[6]].data
Yes, they're being plotted on the first page of plots (lines 72-93).

2020-07-23 22:05 UTC, cmccormick1 commented on general.py
>          detect[11] = 0.5
Yes, this was a temporary fix until the common validation table is sorted out or until I can think of a better solution. One of the mass-LHbeta bins had a bad fit, so we needed to manually exclude it in the validation table.

2020-07-24 16:02 UTC, cmccormick1 commented on general.py
> +    return {cols[ii]:tbl[cols[ii]].data for ii in range(len(cols))}
Used pandas built in function, and table_to_dict() was moved from general.py to __init__.py

2020-07-24 16:11 UTC, astrochun requested changes
Additional changes. Did not get to examine every change in detail.

2020-07-24 16:11 UTC, astrochun commented on Analysis/emission_line_fit.py
>              o1, o2 = curve_fit(gauss, x0[x_idx], y_norm[x_idx], p0 = p0, sigma = None, bounds = para_bound)
```suggestion
            o1, o2 = curve_fit(gauss, x0[x_idx], y_norm[x_idx], p0=p0, sigma=None, bounds=para_bound)
```

2020-07-24 16:11 UTC, astrochun commented on Analysis/emission_line_fit.py
>              o1, o2 = curve_fit(double_gauss, x0[x_idx], y_norm[x_idx], p0 = p0, sigma = None, bounds = para_bound)
```suggestion
            o1, o2 = curve_fit(double_gauss, x0[x_idx], y_norm[x_idx], p0=p0, sigma=None, bounds=para_bound)
```

2020-07-24 16:11 UTC, astrochun commented on Analysis/emission_line_fit.py
> +                               bounds = para_bound)
```suggestion
            o1, o2 = curve_fit(oxy2_gauss, x0[x_idx], y_norm[x_idx], p0=p0, sigma=None, 
                               bounds=para_bound)
```

2020-07-24 16:11 UTC, astrochun commented on Analysis/emission_line_fit.py
>              t_ax.plot(wave, y_norm, 'k', linewidth = 0.6, label = 'Emission')
```suggestion
            t_ax.plot(wave, y_norm, 'k', linewidth=0.6, label='Emission')
```

2020-07-24 16:11 UTC, astrochun commented on Analysis/emission_line_fit.py
> +                                  va = 'top', ha = 'right', fontsize = '8')
```suggestion
                    t_ax.annotate('HbBin:%.2f' % (rr + 1), [0.45, 0.84], xycoords='axes fraction', 
                                  va='top', ha='right', fontsize='8')
```

2020-07-24 16:11 UTC, astrochun commented on Analysis/emission_line_fit.py
> +                              fontsize = '8')
```suggestion
                t_ax.annotate(str1, [0.97, 0.98], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
                t_ax.annotate(str2, [0.97, 0.91], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
                t_ax.annotate(str3, [0.97, 0.84], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
                t_ax.annotate(str4, [0.97, 0.77], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
                t_ax.annotate(str5, [0.97, 0.70], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
                t_ax.annotate(str6, [0.45, 0.98], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
                t_ax.annotate(str7, [0.45, 0.91], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
```

2020-07-24 16:11 UTC, astrochun commented on Analysis/emission_line_fit.py
> +                                  va = 'top', ha = 'right', fontsize = '8')
```suggestion
                    t_ax.annotate('HbBin:%.2f' % (rr + 1), [0.45, 0.84], xycoords='axes fraction', 
                                  va='top', ha='right', fontsize='8')
```

2020-07-24 16:11 UTC, astrochun commented on Analysis/emission_line_fit.py
> +                              fontsize = '8')
```suggestion
                t_ax.annotate(str1, [0.97, 0.98], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
                t_ax.annotate(str2, [0.97, 0.91], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
                t_ax.annotate(str3, [0.97, 0.84], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
                t_ax.annotate(str4, [0.97, 0.77], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
                t_ax.annotate(str5, [0.45, 0.98], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
                t_ax.annotate(str6, [0.45, 0.91], xycoords='axes fraction', va='top', ha='right', 
                              fontsize='8')
```

2020-07-24 16:11 UTC, astrochun commented on Analysis/emission_line_fit.py
>                  t_ax.axvline(x = x, linewidth = 0.3, color = 'k')
```suggestion
                t_ax.axvline(x=x, linewidth=0.3, color='k')
```

2020-07-24 16:11 UTC, astrochun commented on Analysis/emission_line_fit.py
> +                                   hbeta_bin = hbeta_bin)
```suggestion
        em_table = zoom_gauss_plot(pdf_pages, N, wave, Spect_1D, dispersion, s2, lambda0, lambda0[ii], 
                                   curr_line_cols, line_type=line_type[ii], line_name=line_name[ii], 
                                   hbeta_bin=hbeta_bin)
```

2020-07-24 16:11 UTC, astrochun commented on Analysis/indiv_gals.py
> +def indiv_bin_info_table(fitspath, line_file, use_revised = False):
```suggestion
def indiv_bin_info_table(fitspath, line_file, use_revised=False):
```

2020-07-24 16:11 UTC, astrochun commented on Analysis/library.py
> +                 logLHb_min = lowest_hbeta, logLHb_max = highest_hbeta, logLHb_avg = lum_avg,
You might consider passing in a `dict` with all of this information.

2020-07-24 16:11 UTC, astrochun commented on Analysis/library.py
> +                             highest_hbeta, lum_avg, lhb_median], names = all_column_names)
If you do use a `dict` above, you can drop elements and pass it into Table, simplifying things.

2020-07-24 16:11 UTC, astrochun commented on Plotting/composite_plots.py
> +                              color = pt_color)
```suggestion
            ax1[1, 2].scatter(logM_avg[non_detect[ii]], logLHb_avg[non_detect[ii]], marker='^', 
                              color=pt_color)
```

2020-07-24 16:11 UTC, astrochun commented on Plotting/composite_plots.py
> +                          color = pt_color)
```suggestion
        ax1[0, 2].scatter(logM_avg[non_detect[ii]], log_twoBeta[non_detect[ii]], marker='^', 
                          color=pt_color)
        ax1[1, 0].scatter(logM_avg[non_detect[ii]], log_threeBeta[non_detect[ii]], marker='^', 
                          color=pt_color)
```

2020-07-24 16:11 UTC, astrochun commented on Plotting/composite_plots.py
> +                       fontsize = '7')
```suggestion
    ax1[0, 0].annotate('$R_{23}$', [0.05, 0.97], xycoords = 'axes fraction', va='top', ha='left', 
                       fontsize='7')
    ax1[0, 1].annotate('$O_{32}$', [0.05, 0.97], xycoords = 'axes fraction', va='top', ha = 'left', 
                       fontsize='7')
    ax1[0, 2].annotate('[OII]/H$\\beta$', [0.05, 0.97], xycoords='axes fraction', va='top', ha='left', 
                       fontsize='7')
    ax1[1, 0].annotate('[OIII]/H$\\beta$', [0.05, 0.97], xycoords='axes fraction', va='top', ha='left', 
                       fontsize='7')
```

2020-07-24 16:11 UTC, astrochun commented on Plotting/composite_plots.py
> +                       fontsize = '7')
You might find that a for loop passing in a `zip()` of the matplotlib ax and the annotation string more simpler.

2020-07-24 16:11 UTC, astrochun commented on Plotting/composite_plots.py
> +                     fmt = '.')
```suggestion
        ax4.errorbar(logR23[detect], com_O_log[detect], yerr=err_dict['12+log(O/H)_lowhigh_error'], 
                     fmt='.')
```

2020-07-24 16:11 UTC, astrochun commented on Plotting/composite_plots.py
> +                     fmt = '.')
```suggestion
        ax5.errorbar(logO32[detect], com_O_log[detect], yerr=err_dict['12+log(O/H)_lowhigh_error'], 
                     fmt='.')
```

2020-07-31 15:30 UTC, astrochun reviewed
Looks good.

Create new issues for anything that is not addressed (e.g., simplification with dictionary)

2020-08-14 13:30 UTC, merged